import type { Metadata } from "next"
import "./globals.css"
import { montserrat, poppins } from "@/utils/fonts"

export const metadata: Metadata = {
  title: "Paquetá Calçados - Loja de calçados e moda online",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${poppins} ${montserrat}`}>{children}</body>
    </html>
  )
}
